suppressMessages(library(argparser))
suppressMessages(library(tidyverse))

p <- arg_parser("Freesurfer Estimation Consolidation.", hide.opts = FALSE)
p <- add_argument(p, "--mainpath", short = '-m', help = "Specify the main path where Freesurfer statistics can be found.")
argv <- parse_args(p)
main_path = argv$mainpath

participants = list.files(paste0(main_path, "/data"))
outdir = paste0(main_path, "/stats/freesurfer")
dir.create(outdir, recursive = TRUE)

thick_lh_df = data.frame()
thick_rh_df = data.frame()
area_lh_df = data.frame()
area_rh_df = data.frame()
volume_lh_df = data.frame()
volume_rh_df = data.frame()
thicknessstd_lh_df = data.frame()
thicknessstd_rh_df = data.frame()
meancurv_lh_df = data.frame()
meancurv_rh_df = data.frame()
gauscurv_lh_df = data.frame()
gauscurv_rh_df = data.frame()
foldind_lh_df = data.frame()
foldind_rh_df = data.frame()
curvind_lh_df = data.frame()
curvind_rh_df = data.frame()
df_seg = data.frame()
for (p in participants){
    sessions = list.files(paste0(main_path, "/data/", p))
    for (s in sessions){
        thick_lh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/lh_cortical_thickness.csv"))
        thick_lh_df = rbind(thick_lh_df, thick_lh_df_sub)
        thick_rh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/rh_cortical_thickness.csv"))
        thick_rh_df = rbind(thick_rh_df, thick_rh_df_sub)

        area_lh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/lh_cortical_area.csv"))
        area_lh_df = rbind(area_lh_df, area_lh_df_sub)
        area_rh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/rh_cortical_area.csv"))
        area_rh_df = rbind(area_rh_df, area_rh_df_sub)

        volume_lh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/lh_cortical_volume.csv"))
        volume_lh_df = rbind(volume_lh_df, volume_lh_df_sub)
        volume_rh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/rh_cortical_volume.csv"))
        volume_rh_df = rbind(volume_rh_df, volume_rh_df_sub)

        thicknessstd_lh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/lh_cortical_thicknessstd.csv"))
        thicknessstd_lh_df = rbind(thicknessstd_lh_df, thicknessstd_lh_df_sub)
        thicknessstd_rh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/rh_cortical_thicknessstd.csv"))
        thicknessstd_rh_df = rbind(thicknessstd_rh_df, thicknessstd_rh_df_sub)

        meancurv_lh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/lh_cortical_meancurv.csv"))
        meancurv_lh_df = rbind(meancurv_lh_df, meancurv_lh_df_sub)
        meancurv_rh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/rh_cortical_meancurv.csv"))
        meancurv_rh_df = rbind(meancurv_rh_df, meancurv_rh_df_sub)

        gauscurv_lh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/lh_cortical_gauscurv.csv"))
        gauscurv_lh_df = rbind(gauscurv_lh_df, gauscurv_lh_df_sub)
        gauscurv_rh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/rh_cortical_gauscurv.csv"))
        gauscurv_rh_df = rbind(gauscurv_rh_df, gauscurv_rh_df_sub)

        foldind_lh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/lh_cortical_foldind.csv"))
        foldind_lh_df = rbind(foldind_lh_df, foldind_lh_df_sub)
        foldind_rh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/rh_cortical_foldind.csv"))
        foldind_rh_df = rbind(foldind_rh_df, foldind_rh_df_sub)

        curvind_lh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/lh_cortical_curvind.csv"))
        curvind_lh_df = rbind(curvind_lh_df, curvind_lh_df_sub)
        curvind_rh_df_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/rh_cortical_curvind.csv"))
        curvind_rh_df = rbind(curvind_rh_df, curvind_rh_df_sub)

        df_seg_sub = read_csv(paste0(main_path, "/data/", p, "/", s, "/freesurfer/stats_csv/aseg.csv"))
        df_seg = rbind(df_seg, df_seg_sub)
    }
    write_csv(thick_lh_df, paste0(outdir, "/lh_cortical_thickness.csv"))
    write_csv(thick_rh_df, paste0(outdir, "/rh_cortical_thickness.csv"))
    write_csv(area_lh_df, paste0(outdir, "/lh_cortical_area.csv"))
    write_csv(area_rh_df, paste0(outdir, "/rh_cortical_area.csv"))
    write_csv(volume_lh_df, paste0(outdir, "/lh_cortical_volume.csv"))
    write_csv(volume_rh_df, paste0(outdir, "/rh_cortical_volume.csv"))
    write_csv(thicknessstd_lh_df, paste0(outdir, "/lh_cortical_thicknessstd.csv"))
    write_csv(thicknessstd_rh_df, paste0(outdir, "/rh_cortical_thicknessstd.csv"))
    write_csv(meancurv_lh_df, paste0(outdir, "/lh_cortical_meancurv.csv"))
    write_csv(meancurv_rh_df, paste0(outdir, "/rh_cortical_meancurv.csv"))
    write_csv(gauscurv_lh_df, paste0(outdir, "/lh_cortical_gauscurv.csv"))
    write_csv(gauscurv_rh_df, paste0(outdir, "/rh_cortical_gauscurv.csv"))
    write_csv(foldind_lh_df, paste0(outdir, "/lh_cortical_foldind.csv"))
    write_csv(foldind_rh_df, paste0(outdir, "/rh_cortical_foldind.csv"))
    write_csv(curvind_lh_df, paste0(outdir, "/lh_cortical_curvind.csv"))
    write_csv(curvind_rh_df, paste0(outdir, "/rh_cortical_curvind.csv"))
    write_csv(df_seg, paste0(outdir, "/aseg.csv"))
}

